-- LunasTech starter content: devices, symptoms, published guides with steps,
-- and a published simulation for every guide.
--
-- HOW TO RUN: Supabase dashboard > SQL Editor > New query > paste this whole
-- file > Run. The SQL Editor runs with full access, so this bypasses row level
-- security. It is NOT a migration: keep it out of supabase/migrations so the
-- GitHub Action does not deploy it.
--
-- Safe to run more than once: devices and symptoms are matched by name, and a
-- guide that already exists (same symptom and title) is skipped.
-- Everything is inserted as Active / Published so customers see it straight away.
-- Photos are not included; add cover and step photos later in the admin dashboard.

-- ---------- 1. Devices ----------
insert into public.device_types (name, manufacturer, category, status) values
  ('iPhone 13', 'Apple', 'smartphones', 'active'),
  ('Samsung Galaxy S21', 'Samsung', 'smartphones', 'active'),
  ('Dell Inspiron 15', 'Dell', 'laptops', 'active'),
  ('HP Pavilion Desktop', 'HP', 'laptops', 'active'),
  ('iPad (9th gen)', 'Apple', 'tablets', 'active'),
  ('Samsung Galaxy Tab A8', 'Samsung', 'tablets', 'active'),
  ('PlayStation 5', 'Sony', 'game_consoles', 'active'),
  ('Nintendo Switch', 'Nintendo', 'game_consoles', 'active')
on conflict (name) do update
  set manufacturer = excluded.manufacturer,
      category = excluded.category,
      status = 'active';

-- ---------- 2. Symptoms ----------
insert into public.symptoms (device_type_id, name)
select d.id, v.symptom
from (values
  ('iPhone 13', 'Not charging'),
  ('iPhone 13', 'Battery drains fast'),
  ('Samsung Galaxy S21', 'Cracked screen'),
  ('Samsung Galaxy S21', 'Overheating'),
  ('Dell Inspiron 15', 'Won''t turn on'),
  ('Dell Inspiron 15', 'Battery not holding charge'),
  ('Dell Inspiron 15', 'Slow performance'),
  ('HP Pavilion Desktop', 'No Wi-Fi connection'),
  ('iPad (9th gen)', 'Frozen or unresponsive screen'),
  ('iPad (9th gen)', 'Cracked screen'),
  ('Samsung Galaxy Tab A8', 'Not charging'),
  ('PlayStation 5', 'Overheating or loud fan'),
  ('PlayStation 5', 'Disc not reading'),
  ('Nintendo Switch', 'Controller not connecting')
) as v(device, symptom)
join public.device_types d on d.name = v.device
on conflict (device_type_id, name) do nothing;

-- ---------- 3. Guides, steps, simulations ----------
do $seed$
declare
  seed jsonb := $json$[
{"device":"iPhone 13","symptom":"Not charging","title":"Phone won't charge: clean the charging port","description":"Fix a phone that charges slowly or not at all by checking the cable and cleaning lint from the port.","kind":"small_fix","difficulty":"easy","minutes":10,"steps":[{"title":"Try a different cable and adapter","instruction":"Use a cable and wall adapter that you know work. Plug into a wall outlet, not a computer USB port. If the phone charges, the old cable or adapter was the problem."},{"title":"Restart the phone","instruction":"Power the phone off completely, wait 30 seconds, turn it back on, then try charging again."},{"title":"Inspect the charging port","instruction":"Turn the phone off. Shine a flashlight into the charging port and look for lint or dust packed at the bottom."},{"title":"Clean the port gently","instruction":"Use a wooden or plastic toothpick to lightly scrape out the lint. Never use metal or liquids, and do not bend the contacts."},{"title":"Test charging","instruction":"Plug the phone in and wait a few minutes. If there is still no charging icon, the port or battery needs a professional repair."}],"sim":{"title":"Charging problem check","questions":[{"q":"What should you try first when a phone will not charge?","options":["Factory reset the phone","Open the phone","Replace the battery","Try a different cable and adapter"],"correct":3,"feedback":"Cables and adapters fail most often, so test them first."},{"q":"Which tool is safe for cleaning lint out of a charging port?","options":["A wooden or plastic toothpick","A kitchen knife","Water","A metal paperclip"],"correct":0,"feedback":"Metal and liquid can damage the contacts or short-circuit the port."},{"q":"Before cleaning the port, you should...","options":["Turn the phone off","Plug it in","Raise the screen brightness","Remove the case only"],"correct":0,"feedback":"Cleaning a powered-on phone risks a short circuit."},{"q":"The phone charges fine with a different cable. What was the likely problem?","options":["The charging port","The software","The original cable or adapter","The screen"],"correct":2,"feedback":"If another cable works, the first cable or adapter is faulty."},{"q":"You cleaned the port and it still will not charge. What next?","options":["Spray liquid into the port","Ignore it","Push the toothpick deeper","Get a professional repair"],"correct":3,"feedback":"A deeper fault, such as a damaged port or worn battery, needs a technician."}]}},
{"device":"iPhone 13","symptom":"Battery drains fast","title":"Battery drains fast: check battery health and settings","description":"Find out what is using your battery and change a few settings so it lasts longer.","kind":"small_fix","difficulty":"easy","minutes":15,"steps":[{"title":"Check battery health","instruction":"Open Settings, then Battery, then Battery Health & Charging. If Maximum Capacity is well below 80%, the battery is worn and may need replacing."},{"title":"See which apps use the most power","instruction":"In Settings, then Battery, scroll to the usage list. Note any app that uses far more than the others."},{"title":"Lower brightness and set Auto-Lock","instruction":"Turn on Auto-Brightness or lower the brightness. Set Auto-Lock to 30 seconds or 1 minute."},{"title":"Limit background activity","instruction":"In Settings, then General, then Background App Refresh, turn it off for apps you do not need. Turn on Low Power Mode when the battery is low."},{"title":"Update the software","instruction":"Open Settings, then General, then Software Update and install any update. Then watch your battery use for a day."}],"sim":{"title":"Battery drain check","questions":[{"q":"Where do you check how worn the battery is?","options":["Settings > Sounds","Settings > Wallpaper","Settings > Battery > Battery Health & Charging","The Camera app"],"correct":2,"feedback":"Battery Health shows the maximum capacity compared to when the battery was new."},{"q":"Maximum Capacity shows 72%. What does that suggest?","options":["Nothing, it is normal","The battery is brand new","The battery is worn and may need replacing","The screen is broken"],"correct":2,"feedback":"Capacity well below 80% means the battery holds much less charge than it used to."},{"q":"Which setting reduces background power use?","options":["Turning off Background App Refresh for apps you do not need","Turning off Auto-Lock","Setting brightness to maximum","Keeping many apps open"],"correct":0,"feedback":"Apps refreshing in the background use power even when you are not using them."},{"q":"After changing settings, how should you judge the result?","options":["Check after one minute","Watch battery use for a day or so","Restart ten times","Factory reset straight away"],"correct":1,"feedback":"Battery use varies through the day, so give it time before deciding."}]}},
{"device":"Samsung Galaxy S21","symptom":"Cracked screen","title":"Replace a cracked phone screen","description":"Replace a cracked screen with a new one. This repair needs patience and the right tools.","kind":"major_repair","difficulty":"hard","minutes":60,"steps":[{"title":"Back up your data and power off","instruction":"Back up your photos and files, then power the phone off completely. Remove the SIM tray."},{"title":"Gather your tools","instruction":"You need a replacement screen made for your exact model, a suction cup, plastic pry tools, a small Phillips screwdriver, a hair dryer or heat pad, and tweezers. The opening method differs between phones, so check a teardown guide for your model."},{"title":"Soften the adhesive","instruction":"Warm the edges of the phone with a hair dryer or heat pad for 1 to 2 minutes. Do not overheat it."},{"title":"Open the phone and disconnect the battery","instruction":"Slide a plastic pry tool into the seam and work around the edge. Remove the shield screws and disconnect the battery connector before touching anything else."},{"title":"Remove the old screen","instruction":"Disconnect the screen cable, lift the old screen free and clean old adhesive from the frame. Move over any parts that are not on the new screen."},{"title":"Test the new screen","instruction":"Connect the new screen and reconnect the battery. Power on and check touch, display and brightness before sealing."},{"title":"Seal and run a final test","instruction":"Power off and disconnect the battery again. Apply new adhesive, press the screen into place and let it rest under light pressure. Power on and test again."}],"sim":{"title":"Screen replacement check","questions":[{"q":"What must you do before touching other internal parts?","options":["Remove the screen protector","Plug the phone into a charger","Disconnect the battery","Turn the brightness up"],"correct":2,"feedback":"A connected battery can cause a short circuit while you work."},{"q":"Why do you warm the edges of the phone?","options":["To clear the phone's cache","To soften the adhesive","To dry the screen","To charge the battery"],"correct":1,"feedback":"Warm adhesive lets the screen separate with less force and less risk of damage."},{"q":"When should you test the new screen?","options":["Never","Only after the adhesive fully sets","Before sealing the phone","After a week of use"],"correct":2,"feedback":"Testing first means you can fix a bad connection without breaking the new seal."},{"q":"Which tool is best for prying the phone open?","options":["A plastic pry tool","A hammer","A metal screwdriver","A kitchen knife"],"correct":0,"feedback":"Plastic will not scratch the frame or cut cables the way metal can."}]}},
{"device":"Samsung Galaxy S21","symptom":"Overheating","title":"Cool down an overheating phone","description":"Learn what makes a phone run hot and how to bring the temperature down safely.","kind":"small_fix","difficulty":"easy","minutes":10,"steps":[{"title":"Stop heavy use and unplug","instruction":"Close games and video apps and unplug the charger. Let the phone rest for a few minutes."},{"title":"Remove the case and move to shade","instruction":"Take off the case and keep the phone out of direct sun and hot places such as a parked car. Do not put it in a fridge or freezer."},{"title":"Close background apps and restart","instruction":"Close apps you are not using, then restart the phone."},{"title":"Update apps and software","instruction":"Install any pending updates. A faulty app can keep the processor busy and make the phone hot."}],"sim":{"title":"Overheating check","questions":[{"q":"What should you do first when a phone is very hot?","options":["Wrap it in a blanket","Keep playing the game","Put it in the freezer","Stop heavy use and unplug it"],"correct":3,"feedback":"Heavy use and charging both create heat, so stop them first."},{"q":"Why should you not put a hot phone in the freezer?","options":["There is no reason","It would charge the battery","It would delete your data","Sudden cold can cause condensation and damage"],"correct":3,"feedback":"Rapid temperature changes can create moisture inside the phone."},{"q":"Which situation makes overheating worse?","options":["Charging while gaming in direct sunlight","Resting the phone in the shade","Closing unused apps","Removing the case"],"correct":0,"feedback":"Charging, heavy use and sunlight all add heat at the same time."},{"q":"The phone still overheats after an update and restart. What next?","options":["Contact a technician because the battery may be faulty","Charge it overnight under a pillow","Ignore it","Hit the back of the phone"],"correct":0,"feedback":"A phone that stays hot may have a failing battery, which should be checked."}]}},
{"device":"Dell Inspiron 15","symptom":"Won't turn on","title":"Laptop won't turn on: check power and cables","description":"Work through the simple checks that fix most laptops that appear dead.","kind":"small_fix","difficulty":"easy","minutes":15,"steps":[{"title":"Check the charger and outlet","instruction":"Plug the charger into a different wall outlet. Look at the cable for damage and check that the charger light, if it has one, is on."},{"title":"Check the charging light","instruction":"Look for the charging light on the laptop. Push the charger plug in firmly and try again."},{"title":"Do a power reset","instruction":"Unplug the charger and all accessories. Hold the power button for 15 to 30 seconds, then plug the charger back in and press the power button."},{"title":"Disconnect extra devices","instruction":"Unplug USB drives, printers and external monitors, then try turning the laptop on again."},{"title":"Check the screen","instruction":"If the lights and fan come on but the screen is black, shine a flashlight at the screen to look for a faint image, or connect an external monitor. If neither works, take it for service."}],"sim":{"title":"Laptop power check","questions":[{"q":"What should you check first when a laptop will not turn on?","options":["The hard drive","The Wi-Fi","The keyboard","The charger and wall outlet"],"correct":3,"feedback":"A dead outlet or damaged charger is the most common cause."},{"q":"Why hold the power button for 15 to 30 seconds?","options":["To format the drive","To update Windows","To drain leftover power and reset the hardware","To clean the fans"],"correct":2,"feedback":"A power reset can clear a stuck state that stops the laptop starting."},{"q":"Why unplug USB drives and other devices?","options":["To clear the memory","A faulty device can stop the laptop from starting","To save electricity","To speed up the screen"],"correct":1,"feedback":"Removing extras helps you find out whether one of them is the cause."},{"q":"The fan runs but the screen is black. What can you try?","options":["Throw the laptop away","Pour water on the keyboard","Look for a faint image with a flashlight or use an external monitor","Reinstall the battery cable"],"correct":2,"feedback":"Both checks show whether the laptop works and only the screen backlight has failed."}]}},
{"device":"Dell Inspiron 15","symptom":"Battery not holding charge","title":"Replace a worn laptop battery","description":"Check that the battery is the problem, then swap in a new one safely.","kind":"major_repair","difficulty":"moderate","minutes":45,"steps":[{"title":"Confirm the battery is the problem","instruction":"Open Command Prompt and type powercfg /batteryreport. Open the report and compare Full Charge Capacity with Design Capacity. A big gap means the battery is worn."},{"title":"Buy the right battery","instruction":"Use the exact part number from the label on the old battery or from the manufacturer's support page. Cheap unbranded batteries can be unsafe."},{"title":"Shut down and unplug","instruction":"Shut the laptop down fully, unplug the charger and all cables, and place it upside down on a soft, clean surface."},{"title":"Open the back panel","instruction":"Remove the screws with a Phillips screwdriver and lift the panel gently with a plastic pry tool. Keep the screws organised."},{"title":"Disconnect and remove the old battery","instruction":"Unplug the battery cable from the motherboard, unscrew the battery and lift it out. Do not puncture or bend it."},{"title":"Install the new battery","instruction":"Place the new battery, screw it down and connect the cable. Put the panel and screws back."},{"title":"Recycle the old battery and test","instruction":"Take the old battery to an e-waste or battery recycling point. Never put it in household rubbish. Charge the new battery fully and check the battery report again."}],"sim":{"title":"Battery replacement check","questions":[{"q":"Which command creates a battery report in Windows?","options":["powercfg /batteryreport","ipconfig /all","format c:","shutdown /s"],"correct":0,"feedback":"The report compares the battery's full charge capacity with its original design capacity."},{"q":"What must you do before opening the laptop?","options":["Shut it down and unplug everything","Put it to sleep","Leave the charger connected","Only dim the screen"],"correct":0,"feedback":"Working on a powered laptop risks electric shock and damage to the motherboard."},{"q":"How should you dispose of the old battery?","options":["Take it to an e-waste or battery recycling point","Put it in the household bin","Leave it plugged in","Burn it"],"correct":0,"feedback":"Lithium batteries can start fires in bins and landfill, so they must be recycled."},{"q":"Which replacement battery should you buy?","options":["Any battery that looks about right","One that matches the exact part number","The cheapest unbranded one","A phone battery"],"correct":1,"feedback":"The wrong battery may not fit, may not charge correctly, or may be unsafe."}]}},
{"device":"Dell Inspiron 15","symptom":"Slow performance","title":"Slow computer: free up storage and startup apps","description":"Speed up a slow Windows computer by finding what is using resources and cleaning up.","kind":"small_fix","difficulty":"easy","minutes":20,"steps":[{"title":"Restart the computer","instruction":"A computer left on for days can slow down. Save your work and restart it."},{"title":"Check what is using resources","instruction":"Press Ctrl + Shift + Esc to open Task Manager. On the Processes tab, click the CPU and Memory columns to sort them and see which apps use the most."},{"title":"Turn off startup apps","instruction":"In Task Manager, open Startup apps and disable the ones you do not need to run when the computer starts."},{"title":"Free up storage","instruction":"Delete files you do not need, empty the Recycle Bin and uninstall programs you no longer use. Try to keep at least 15% of the drive free."},{"title":"Update and scan","instruction":"Run Windows Update, then run a full scan with Windows Security to check for malware."}],"sim":{"title":"Slow computer check","questions":[{"q":"Which shortcut opens Task Manager?","options":["Windows key + L","Ctrl + Shift + Esc","Ctrl + C","Alt + F4"],"correct":1,"feedback":"Task Manager shows which apps are using the most CPU and memory."},{"q":"What does disabling a startup app do?","options":["It formats the drive","It deletes the app","It does nothing at all","It stops the app launching when the computer starts"],"correct":3,"feedback":"Fewer startup apps means a faster start and less background load."},{"q":"Why keep free space on the drive?","options":["It lowers the Wi-Fi speed","A nearly full drive slows the computer down","Free space makes the screen brighter","It has no effect"],"correct":1,"feedback":"Windows needs free space to work with temporary files."},{"q":"Why run a full Windows Security scan?","options":["Malware can use resources and slow the computer","It speeds up the fan","It charges the battery","It uninstalls old apps"],"correct":0,"feedback":"Hidden malicious programs can use a lot of processing power."}]}},
{"device":"HP Pavilion Desktop","symptom":"No Wi-Fi connection","title":"No Wi-Fi: reset the network connection","description":"Fix a computer that will not connect to Wi-Fi by working from the simplest check to the biggest reset.","kind":"small_fix","difficulty":"easy","minutes":15,"steps":[{"title":"Check Wi-Fi is on","instruction":"Make sure Airplane mode is off and Wi-Fi is turned on in the taskbar. Check whether other devices can connect to the same network."},{"title":"Restart the router and computer","instruction":"Unplug the router for 30 seconds, plug it back in and wait 2 minutes. Then restart the computer."},{"title":"Forget the network and reconnect","instruction":"Open Settings, then Network & internet, then Wi-Fi, then Manage known networks. Select your network, choose Forget, then connect again with the password."},{"title":"Run the network troubleshooter","instruction":"Open Settings, then System, then Troubleshoot, then Other troubleshooters, and run Network and Internet."},{"title":"Reset the network as a last resort","instruction":"Open Settings, then Network & internet, then Advanced network settings, then Network reset. The computer restarts and you must enter your Wi-Fi passwords again."}],"sim":{"title":"Wi-Fi problem check","questions":[{"q":"Other devices cannot connect to the Wi-Fi either. Where is the problem likely to be?","options":["The router or internet service","Your computer's keyboard","Your computer's screen","Your mouse"],"correct":0,"feedback":"If nothing connects, the fault is outside your computer."},{"q":"Why restart the router?","options":["It deletes your files","It clears temporary glitches","It upgrades your computer","It makes the screen brighter"],"correct":1,"feedback":"Routers can get stuck after running for a long time."},{"q":"What do you need after choosing Forget on a network?","options":["The Wi-Fi password","A new computer","A new router","A USB drive"],"correct":0,"feedback":"Forgetting the network removes the saved password."},{"q":"Which step should you leave until last?","options":["Running the troubleshooter","Restarting the router","Checking Wi-Fi is on","Network reset"],"correct":3,"feedback":"Network reset removes saved networks and settings, so use it only if the other steps fail."}]}},
{"device":"iPad (9th gen)","symptom":"Frozen or unresponsive screen","title":"Frozen iPad: force restart","description":"Get a frozen iPad working again without losing your data.","kind":"small_fix","difficulty":"easy","minutes":5,"steps":[{"title":"Wait and try again","instruction":"Wait a minute in case the iPad is busy, then try swiping or tapping again."},{"title":"Charge it briefly","instruction":"Plug the iPad in for 15 to 30 minutes in case the battery is empty. Look for the charging icon."},{"title":"Force restart","instruction":"Press and hold the Top button and the Home button together for 10 seconds or more, until the Apple logo appears. This is for the iPad 9th generation, which has a Home button."},{"title":"Update when it is working","instruction":"Open Settings, then General, then Software Update and install any update."}],"sim":{"title":"Frozen iPad check","questions":[{"q":"What should you try first on a frozen iPad?","options":["Open it up","Reset it to factory settings","Wait a minute and try again","Throw it away"],"correct":2,"feedback":"Sometimes the iPad is just busy and recovers by itself."},{"q":"Which buttons force restart an iPad 9th generation?","options":["Only the volume button","Volume up and volume down","Top button and Home button together","The camera button"],"correct":2,"feedback":"Holding both buttons forces the iPad to restart."},{"q":"The screen is black and the iPad does not respond. What should you do before force restarting?","options":["Take off the screen","Charge it for 15 to 30 minutes","Delete all your apps","Leave it in the sun"],"correct":1,"feedback":"A completely empty battery looks like a frozen screen."},{"q":"Why update the software after it works again?","options":["Updates fix bugs that can cause freezing","There is no reason","Updates delete your photos","Updates make the screen larger"],"correct":0,"feedback":"Bug fixes in updates help stop the problem coming back."}]}},
{"device":"iPad (9th gen)","symptom":"Cracked screen","title":"Replace a cracked tablet screen","description":"Replace the broken glass on a tablet. This is a careful repair that takes time and patience.","kind":"major_repair","difficulty":"hard","minutes":75,"steps":[{"title":"Back up and power off","instruction":"Back up the iPad to iCloud or a computer, then power it off. Cover the cracked glass with clear packing tape to hold shards together, and wear safety glasses."},{"title":"Gather your tools","instruction":"You need a replacement screen for the exact model, a hair dryer or heat pad, a suction cup, thin plastic picks, small screwdrivers and adhesive strips."},{"title":"Heat and loosen the screen edges","instruction":"Warm the edges gently to soften the glue. Work the plastic picks in slowly and separate the screen a little at a time to avoid cracking more glass or cutting cables."},{"title":"Disconnect the battery and cables","instruction":"Lift the screen carefully. Disconnect the battery first, then the display and touch cables."},{"title":"Clean the frame and move parts across","instruction":"Remove old glue and glass pieces from the frame. Move the Home button and any parts that are not on the new screen."},{"title":"Test before sealing","instruction":"Connect the new screen and battery, power on, and test touch across the whole screen and the Home button."},{"title":"Seal and finish","instruction":"Power off, disconnect the battery, apply adhesive and press the screen into place. Let it rest under light weight for several hours before heavy use."}],"sim":{"title":"Tablet screen check","questions":[{"q":"Which connection do you disconnect first?","options":["The speaker","The battery","The camera","The display cable"],"correct":1,"feedback":"Disconnecting power first protects the iPad's circuits while you work."},{"q":"Why go slowly when loosening the screen?","options":["To make the glue stronger","To save electricity","There is no reason","To avoid cracking more glass or cutting cables"],"correct":3,"feedback":"Cables sit just under the glass and are easy to cut."},{"q":"Why put clear tape over the cracked screen?","options":["To make the screen brighter","To clean the screen","To charge the battery","To hold glass shards together safely"],"correct":3,"feedback":"Tape stops small pieces of glass from falling out and hurting you."},{"q":"When should you test the new screen?","options":["Only when it is cracked again","Never","Before sealing it","After it has been sealed for a week"],"correct":2,"feedback":"Testing first lets you fix any loose connection before the glue sets."}]}},
{"device":"Samsung Galaxy Tab A8","symptom":"Not charging","title":"Tablet not charging: check the cable and clean the port","description":"Find out whether the charger, cable or port is stopping your tablet from charging.","kind":"small_fix","difficulty":"easy","minutes":10,"steps":[{"title":"Try another cable and charger","instruction":"Use the original charger or one rated for the tablet, and plug it into a working wall outlet."},{"title":"Check the cable ends and port","instruction":"Look at both ends of the cable for bent or dirty pins. Shine a flashlight into the tablet's USB-C port and look for lint."},{"title":"Clean the USB-C port","instruction":"Power the tablet off. Remove lint with a wooden toothpick or soft brush. Do not use metal or liquids."},{"title":"Force restart","instruction":"Hold the Power and Volume Down buttons together for about 10 seconds until the tablet restarts."},{"title":"Give it time to charge","instruction":"If the battery was empty for a long time, leave it on the charger for 30 minutes before deciding. If it still does nothing, take it for service."}],"sim":{"title":"Tablet charging check","questions":[{"q":"Which charger is best to use?","options":["The original charger or one rated for the tablet","Any old cable you find","A metal wire","A damaged charger"],"correct":0,"feedback":"The right charger gives the correct power and protects the battery."},{"q":"What can you use to clean lint from the port?","options":["Water","A screwdriver","A wooden toothpick or soft brush","A metal pin"],"correct":2,"feedback":"Soft tools clean the port without damaging the contacts."},{"q":"Which buttons force restart this tablet?","options":["Volume Up and Volume Down only","Power and Volume Down together","Home button only","Camera button"],"correct":1,"feedback":"Holding both buttons restarts the tablet even when it is frozen."},{"q":"The battery has been empty for a long time. What should you do?","options":["Open the case at once","Leave it on the charger for 30 minutes before deciding","Give up straight away","Restart it every few seconds"],"correct":1,"feedback":"A deeply drained battery needs time before it shows any sign of charging."}]}},
{"device":"PlayStation 5","symptom":"Overheating or loud fan","title":"Console overheating: clean vents and improve airflow","description":"Reduce fan noise and heat by improving airflow and removing dust.","kind":"small_fix","difficulty":"moderate","minutes":30,"steps":[{"title":"Check where the console is placed","instruction":"Put the console where air can flow freely, with space around the vents. Keep it out of closed cabinets and away from heaters or direct sunlight."},{"title":"Power off and unplug","instruction":"Turn the console off completely, not rest mode. Unplug the power and all cables and let it cool down."},{"title":"Remove the side cover","instruction":"Lift one corner of the side cover and slide it off, following the console's cover removal instructions."},{"title":"Remove dust from the vents","instruction":"Use a vacuum with a soft brush attachment or short bursts of compressed air at the vents. Do not push the nozzle into the console or touch the parts inside."},{"title":"Put the cover back and reconnect","instruction":"Slide the cover back on, reconnect the cables and power on."},{"title":"Update and monitor","instruction":"Install any system software update. Listen to the fan during a game and check whether it is quieter."}],"sim":{"title":"Console cooling check","questions":[{"q":"Where is the best place to put a console?","options":["Under a blanket","Inside a closed cabinet","In open space with good airflow","Next to a heater"],"correct":2,"feedback":"Vents need free air to carry heat away."},{"q":"Why unplug the console before cleaning it?","options":["To update the system","To charge the controller","For safety, so there is no power while you work","To make it louder"],"correct":2,"feedback":"Cleaning a connected console risks electric shock and damage."},{"q":"Why not use rest mode before cleaning?","options":["Rest mode cools the vents too much","The console still uses power in rest mode","Rest mode deletes saved games","It does not matter"],"correct":1,"feedback":"Only a full power off, with the plug removed, is safe for cleaning."},{"q":"Which tool is best for removing dust from vents?","options":["A metal rod","A vacuum with a soft brush or short bursts of compressed air","A hair dryer on high heat","A wet cloth pushed inside"],"correct":1,"feedback":"Gentle dust removal protects the fan and the parts inside."}]}},
{"device":"PlayStation 5","symptom":"Disc not reading","title":"Disc not reading: clean the disc and check the drive","description":"Find out whether the disc or the console's drive is causing the problem.","kind":"small_fix","difficulty":"easy","minutes":10,"steps":[{"title":"Check the disc","instruction":"Look for fingerprints and scratches and make sure the disc is the right way up. Note that the Digital Edition has no disc drive."},{"title":"Clean the disc","instruction":"Wipe the disc with a soft, lint-free cloth from the centre outward in straight lines. Do not wipe in circles or use chemicals."},{"title":"Restart the console","instruction":"Turn the console off completely, wait 30 seconds and turn it back on."},{"title":"Try another disc","instruction":"If other discs work, the first disc is probably damaged. If no disc works, the disc drive may need service."}],"sim":{"title":"Disc reading check","questions":[{"q":"In which direction should you wipe a disc?","options":["Side to side with paper towel","With a wet cloth in circles","In circles around the disc","From the centre outward in straight lines"],"correct":3,"feedback":"Straight lines across the disc cause less harm to the data tracks than circular marks."},{"q":"Another disc works but the first one does not. What is likely?","options":["The controller is broken","The TV is broken","The console is broken","The first disc is damaged"],"correct":3,"feedback":"The console can read other discs, so the drive is fine."},{"q":"Which edition of the console has no disc drive?","options":["Every edition has one","The Standard Edition","No edition has one","The Digital Edition"],"correct":3,"feedback":"The Digital Edition only plays downloaded games."},{"q":"No disc reads after cleaning and restarting. What does this suggest?","options":["The disc drive may need service","The disc needs more cleaning","The cable is too long","The controller is dirty"],"correct":0,"feedback":"If every disc fails, the problem is in the drive."}]}},
{"device":"Nintendo Switch","symptom":"Controller not connecting","title":"Re-pair a controller that will not connect","description":"Get a Joy-Con or other controller connecting to the console again.","kind":"small_fix","difficulty":"easy","minutes":10,"steps":[{"title":"Charge the controller","instruction":"Slide the Joy-Con onto the console's side rail and charge for about 30 minutes. A flat battery stops the controller connecting."},{"title":"Update the controllers","instruction":"On the Home menu, open System Settings, then Controllers and Sensors, then Update Controllers."},{"title":"Re-sync the controller","instruction":"Slide the Joy-Con onto the side rail so the console pairs it again. For a wireless re-pair, open Controllers, then Change Grip/Order, and press the small sync button on the controller."},{"title":"Remove interference","instruction":"Move away from routers, microwaves and other wireless devices, and stay within a few metres of the console."},{"title":"Restart the console","instruction":"Hold the Power button for 3 seconds, choose Power Options, then Restart, and try the controller again."}],"sim":{"title":"Controller connection check","questions":[{"q":"What should you check first when a controller will not connect?","options":["The Wi-Fi password","That the controller has enough battery","The TV colour","The game disc"],"correct":1,"feedback":"A flat controller cannot connect."},{"q":"How can a Joy-Con pair again quickly?","options":["Put it in water","Slide it onto the side rail of the console","Hit it against the table","Leave it in a drawer"],"correct":1,"feedback":"Attaching it to the rail re-pairs and charges it."},{"q":"Which of these can interfere with the wireless connection?","options":["A photo frame","A microwave or router close by","A wooden table","A pot plant"],"correct":1,"feedback":"Other wireless devices can disturb the signal."},{"q":"Why update the controllers?","options":["Updates fix connection problems","Updates change the colour of the controller","Updates delete save files","There is no reason"],"correct":0,"feedback":"Firmware updates can resolve known pairing and connection bugs."}]}}
]$json$::jsonb;
  g jsonb;
  st jsonb;
  qu jsonb;
  v_symptom uuid;
  v_guide uuid;
  v_sim uuid;
  v_admin uuid;
  n integer;
  added integer := 0;
begin
  -- Credit the guides to the first admin account, if there is one.
  select id into v_admin from public.profiles where role = 'admin' order by created_at limit 1;

  for g in select * from jsonb_array_elements(seed) loop
    select s.id into v_symptom
    from public.symptoms s
    join public.device_types d on d.id = s.device_type_id
    where d.name = g->>'device' and s.name = g->>'symptom';

    if v_symptom is null then
      raise exception 'Symptom not found: % / %', g->>'device', g->>'symptom';
    end if;

    if exists (select 1 from public.guides where symptom_id = v_symptom and title = g->>'title') then
      continue;
    end if;

    insert into public.guides
      (symptom_id, title, description, kind, difficulty, estimated_minutes, status, created_by)
    values
      (v_symptom, g->>'title', g->>'description', (g->>'kind')::public.guide_kind,
       (g->>'difficulty')::public.guide_difficulty, (g->>'minutes')::integer, 'published', v_admin)
    returning id into v_guide;

    n := 0;
    for st in select * from jsonb_array_elements(g->'steps') loop
      n := n + 1;
      insert into public.guide_steps (guide_id, position, title, instruction)
      values (v_guide, n, st->>'title', st->>'instruction');
    end loop;

    insert into public.simulations (guide_id, title, status)
    values (v_guide, g->'sim'->>'title', 'published')
    returning id into v_sim;

    n := 0;
    for qu in select * from jsonb_array_elements(g->'sim'->'questions') loop
      n := n + 1;
      insert into public.simulation_steps (simulation_id, position, prompt, options, correct_option, feedback)
      values (v_sim, n, qu->>'q', qu->'options', (qu->>'correct')::integer, qu->>'feedback');
    end loop;

    added := added + 1;
  end loop;

  raise notice 'Added % new guides.', added;
end
$seed$;

-- ---------- Check: should list every guide as published ----------
select d.name as device, s.name as symptom, g.title, g.kind, g.status,
       (select count(*) from public.guide_steps gs where gs.guide_id = g.id) as steps,
       (select count(*) from public.simulation_steps ss
         join public.simulations sm on sm.id = ss.simulation_id where sm.guide_id = g.id) as questions
from public.guides g
join public.symptoms s on s.id = g.symptom_id
join public.device_types d on d.id = s.device_type_id
order by d.name, s.name, g.title;
